### ISSUE TITLE
Self provisioning of space

### ISSUE THREAD

**Issue by ALIRAZA17** [RobinNagpal/dodao-ui#117]
For this we need to
- Create a new user
    -  First we need to take all the user details that are required to sign him up to create his/her space
    -  We can have a captcha here to check if the user is human or not
    -  After Validation the next step will be to create a new space
- Create a new space
    - For this there can be a separate form taking all the relevant details for a space
    - Include that user as admin of the space by filling the relevant fields in the database
- Then take the user to the admin screen

This will be the general flow as we can start this on the "Create Tidbit Site" button that is already there for admins

**Comment by RobinNagpal** [comment]
Scenarios
1) User updates their information and exits (Doesn't do anything on screen 2)


2) User creates space and exits (Doesn't do anything after screen 2)
- We first check if a space is present for that user as the creator, in that we pre-populate that information on screen 2. So we are basically allowing only one space per creator
- So we can try to find the first space with that username.

This will help us to make sure user is continuing with that flow.

**Comment by ALIRAZA17** [comment]
#126

**Comment by RobinNagpal** [comment]
Tasks
- [ ] Every screen will have next and previous buttons. The first screen will not have previous Button
- [ ] On the first screen we fetch the user and if its details exist we populate it in the fields. Similarly we have to do for the second step
- [ ] So on second step, we show loading spinner till we check if the space exists or not. 
    - [ ] If the space is not there, we allow the user to create a space
    - [ ] If the space is there we allow the user to edit the name and logo. The id will be readonly. Later on we can remove the Id from the UI to avoid any confusion
    - [ ] If user goes to step 3 and comes back to step 2, step 2 will again check if space exists, and then will show the inputs as populated (name and logo and the user can change these) Now we don't change the id, since the space already exists 
- [ ] On  the third step make sure editing of the Theme looks good
