### ISSUE TITLE
New Design for tidbits

### ISSUE THREAD

**Issue by ALIRAZA17** [RobinNagpal/dodao-ui#138]
We need new tidbits design for banks so we want to have something that goes with the banks.
Currently it looks like this:

![image](https://github.com/RobinNagpal/dodao-ui/assets/75278584/b816b03c-557c-431e-a0d1-3ee336305583)

1) We can change the colours to be focused more towards green and blue because most of the banking systems have these kinds of colours as they show more interest.
2) We can change the progress bar to something related to coins which is closer to banking but im not sure how we can do this here.
3) The main problem that lies is that everything depends upon the theme colours that are coming from backend. And how we can make a generic thing out of this would be a challenge.

Add 15 examples of nano courses sites
1) https://www.learn.xyz
2) https://layer3.xyz/quests/get-started-with-layer3

**Comment by ALIRAZA17** [comment]
1) First design can look like

![image](https://github.com/RobinNagpal/dodao-ui/assets/75278584/458a1f6e-b044-45a0-9466-ea5e45a06378)

2) Another design from learn xyz app

https://github.com/RobinNagpal/dodao-ui/assets/75278584/f89d0170-faca-464d-999a-00c19ef0d2fc

3) Another design from Ed app

Link: https://www.edapp.com/

![image](https://github.com/RobinNagpal/dodao-ui/assets/75278584/00c82414-a17a-4c15-973f-ed92cecc3f4e)

4) From 7Taps

demo link: https://www.7taps.com/

![image](https://github.com/RobinNagpal/dodao-ui/assets/75278584/4db16726-a658-4762-9b13-a1debc9afa4c)

5) https://www.edapp.com/blog/microlearning-apps/

**Comment by RobinNagpal** [comment]
Some more info

https://www.ispringsolutions.com/blog/benefits-of-microlearning

**Comment by RobinNagpal** [comment]
Final Design Details

1. On the top we want to show steps like in learn.xyz
![image](https://github.com/RobinNagpal/dodao-ui/assets/745748/b4f4ec48-682f-47b3-812c-04e8c691d018)

2.  Next we want to show image, heading, and content just like learn.xyz
![image](https://github.com/RobinNagpal/dodao-ui/assets/745748/8f0a8639-b949-41cd-8bf1-9ec111e3a34c)

3. We want to show the bottom buttons like layer3.xyz 
![image](https://github.com/RobinNagpal/dodao-ui/assets/745748/e29a636a-50e5-4ab4-90ce-848710a2bf4a)

4. Layout also can be similar to Layer3.xyz

5. For the transition effect for moving from one step to other, we want to find a library and use it. Whatever library has most amount of stars and is the easiest to use

**Comment by RobinNagpal** [comment]
Tasks

## Backend Tasks
1. Add an optional field in Bytes - `byteStyle`. Type of this field will be "string" not enum.  Refer to space.type 
2. Declare an enum in `bytes.gql`
```
enum ByteStyle {
  CardAndCircleProgress
  CarouselWithProgressBars    
}
```
3. Add a new field in step of Byte  called `imageUrl` which is optional


Make sure to get the backed merged first, before starting on the UI.

## UI Tasks
1. Add a new component which we show based on the byteStyle in the UI
2. No need to add the image field - This will be done by SAMI.

**Comment by RobinNagpal** [comment]
@ALIRAZA17  take a look at these animations also

![image](https://github.com/RobinNagpal/dodao-ui/assets/745748/e35efc94-47df-4394-a61a-c96783f98a07)

https://www.framer.com/motion/examples/

**Comment by RobinNagpal** [comment]
Issues on larger screen

![image](https://github.com/RobinNagpal/dodao-ui/assets/745748/3a8661a0-0511-4704-a41a-c79b3c79a053)

**Comment by RobinNagpal** [comment]
Small screen issues

![image](https://github.com/RobinNagpal/dodao-ui/assets/745748/9f22f0f0-faec-4b03-b903-0f0cc22b945e)
