### ISSUE TITLE
Generate Relevant images for Tidbits

### ISSUE THREAD

**Issue by RobinNagpal** [RobinNagpal/dodao-ui#139]
We will be targeting banks as customer and will be showcasing the usefulness of Tidbits, so the images that are generated should be very relevant.

Add 5 relevant tidbits related to Fraud Prevention on Opportunity Bank Space.

Then try to generate images for each of the steps. Make sure the images are very professional and match the content

Refer to image examples here - https://www.learn.xyz/

**Comment by ALIRAZA17** [comment]
1) First design can look like

![image](https://github.com/RobinNagpal/dodao-ui/assets/75278584/458a1f6e-b044-45a0-9466-ea5e45a06378)

2) Another design from learn xyz app

https://github.com/RobinNagpal/dodao-ui/assets/75278584/f89d0170-faca-464d-999a-00c19ef0d2fc

3) Another design from Ed app

Link: https://www.edapp.com/

![image](https://github.com/RobinNagpal/dodao-ui/assets/75278584/00c82414-a17a-4c15-973f-ed92cecc3f4e)

4) From 7Taps

demo link: https://www.7taps.com/

![image](https://github.com/RobinNagpal/dodao-ui/assets/75278584/4db16726-a658-4762-9b13-a1debc9afa4c)

5)
