### ISSUE TITLE
Research - Bank Education Touch Points - Fraud Prevention and Financial Literacy

### ISSUE THREAD

**Issue by RobinNagpal** [RobinNagpal/dodao-ui#141]
Touch Points(By Grege)

# Fraud Prevention
##### **Challenges**
1. This means they have to share all the SMS templates to us.

**Comment by gregerodrigues** [comment]
We can create a complete fraud education website for bank. By linking this website to the bank's existing platforms and channels, such as online banking platforms, mobile apps, email campaigns, social media channels, and in-branch, ATMs we can ensure widespread visibility and accessibility of the educational resources. we can monitor customer engagement and measure the effectiveness of our educational initiatives.
