### ISSUE TITLE
Add Acedemy site Links

### ISSUE THREAD

**Issue by AreeshaKhalid007** [RobinNagpal/dodao-ui#149]
Create a section within the DoDAO homepage that clearly displays the academy sites for Arbitrum, Optimism, Uniswap, and Compound along with the academy site links.
In the section showing logos of companies worked with add Arbitrum and Optimism as well

**Comment by RobinNagpal** [comment]
Added here https://github.com/RobinNagpal/dodao-ui/issues/155
