### ISSUE TITLE
Add redirection to cryptogelato and tidbit hub

### ISSUE THREAD

**Issue by AreeshaKhalid007** [RobinNagpal/dodao-ui#151]
Within the DoDAO homepage create a section of DoDAO products and mention the Customer education sites (redirection to Cryptogelato and Tidbit Hub), Customised Academy Sites and AI tools as the three products of DoDAO.

**Comment by RobinNagpal** [comment]
Added here - https://github.com/RobinNagpal/dodao-ui/issues/155
