### ISSUE TITLE
DoDAO Home Page Improvement

### ISSUE THREAD

**Issue by RobinNagpal** [RobinNagpal/dodao-ui#174]
## High Level Details
- [x] See if "Welcome to DoDAO: Where Learning Meets Simplicity", can use any design to clearly communicate about our products and offerings. Here we should the summary of the product and offerings and below will be the detailed sections, which we already have.
- [x] Add more clients - Arbitrum and Optimism. Also the size and background of the icons need be consistent 
- [x] TidbitsHub Details - We can include  a gif to show how it works(Show navigating one of the tidbits with images). Also add more content.  
- [x] Academy Websites - We can include  a gif to show how it works(Show navigating one guide and simulation). Probably we can remove the clients from here
- [x] AI Chatbot - Add more content and use some AI generated or images from unspash
- [x] Blockchain Bootcamp -  Any way to embed this or open this PDF in a modal? Or may be show the image of the cover and if user clicks, we should the full PDF in a modal
[01-combined_compressed.pdf](https://github.com/RobinNagpal/dodao-ui/files/14605149/01-combined_compressed.pdf) 
- [x] Blockchain Development - Mention that we have five years of in depth experience in blockchain development, and we partner with Strategic projects, and we help them accelerate the development. You can see many development agency websites to get an idea of what we can add here.

@Neusha1  will be creating a doc with the text updates and will add the screenshots and links from https://tailwindui.com. We can use these components to show the text.

**Comment by ALIRAZA17** [comment]
https://docs.google.com/document/d/1Dm1ypwZwjSMj4dmOvAKS-pI61S1UJHnJskMokMTWFsw/edit
