### ISSUE TITLE
Improve experience for users and admins on Tidbit Site

### ISSUE THREAD

**Issue by RobinNagpal** [RobinNagpal/dodao-ui#175]
## BAckground
- When the user comes to the home page of tidbits site, we want to show them either categories or tidbit collections
- When the user clicks on a category, the will go to the category details screen, where they will see all the collections within that category
- When they clock on the tidbit, it should open in the modal. The URL should also change, like it happens now, so that if they reload the tidbit is shown

## Questions
- Should we create a separate edit page that has all the tabs and then allow editing in the popups?
- How should the editing experience of categories should be good
- How should the editing experience of collections should be good
- How should the editing experience of Tidbits should be good
- When happens when users save or create the tidbit category, collection, or tidbit? Which URL should they be redirected to?
- How will the breadcrumbs work? What exactly will be shown so that it looks appealing to the user?

### View for user
- Create the following routes for all three entities `/tidbits`, `/tidbits-collections` and `/tidbit-collection-categories`
    - remove the logic on `/tidbits-collections` for showing of the categories 
-  On the home page of Tidbits site we apply logic to either show categories or tidbit-collections based on categories exist or not
- On `src/app/tidbit-collection-categories/view/[categoryId]/tidbit-collections`, we show all the collections in a category
    - rename `[categoryId]/tidbit-collection` to  `[categoryId]/tidbit-collections`
    - Add bread crumb logic which displays name of category.
-  On `src/app/tidbit-collection-categories/view/[categoryId]/tidbit-collections/[collectionId]/[tidbitId]` we show the tidbit details
    - We add the  breadcrumb logic which displays name of category, the collection name, and the selected tidbit name.
- On `src/app/tidbit-collections/view/[tidbitCollectionId]/[tidbitId]` we show the tidbits. This follows the existing logic.
    -  This will be used when there are no categories
    -  Show breadcrumb on this page which includes the collection name and the tidbit name

### Edit for Admin
- For editing of the allready created categories or collections, we can show "pencil - edit" icon corresponding to the categories, tidbit-collections or tidbits, and the edit can happen in modal. No need to navigate to the new screens. (Showing the updates can be an issue - May be reload on save?) 
- There can be "+" icon, or a card with "+" icon,  at the categories screen, collections screen, and within the collection at the end, to add tidbit. These will the collection and then add to category, or will add the tidbit and also add to collection.

----
### Updates for Admin 
- Use a clear visual indicator for edit options (pencil icon, "Edit" text), and add some transition on hover
- Auto-focusing the first input field when the modal or page opens to prompt immediate action.
- Enable autosave or confirm if the user tries to close with unsaved changes.
- For view details:
    - `/tidbit-collection-categories/view/[tidbit-categoryId]/tidbit-collections` for tidbit category
    - `/tidbit-collection-categories/view/[tidbit-categoryId]/tidbit-collections` for tidbit collection if the edited collection belongs to a category, else redirect to `/tidbit-collections`
    - redirect to `/tidbit-collection-categories/view/[tidbit-categoryId]/tidbit-collection` for tidbit if the tidbit is edited from tidbit collection card.

### Updates for the users
    - We should also change the redirection when we close the tidbit, it should redirect to `/tidbit-collection-categories/view/[tidbit-categoryId]/tidbit-collection` instead of `/tidbit-collections` (I found this quite annoying)

Optional:
- Drafts: Implement a draft-saving feature that automatically saves the progress for the user to come back to it later.
- Inline Editing: For even simpler tidbits, consider the feasibility of inline editing directly on the card with a single click.

## Changes

----

## For users
- [ ] we want to add bread crumbs to make it easy for user to understand what he is looking at
- [ ] 

## For admins
- [ ] We want to show the tab switcher on the tidbit collections page to make it easier for the admins to go to tidbits tab and edit a tidbit. See - src/components/home/TidbitsSite/TidbitsSiteHome.tsx
- [ ]  After editing the back URLs should be good. Probably we can have editing option on tidbit collection screen itself against each tidbit? Then the admin doesn't have to do a lot of tab switching.
- [ ] 

Solution Options
- [ ]

**Comment by RobinNagpal** [comment]
Fixes
- [ ] Categories are not visible on the home page of Tidbits site
- [ ] Tidbit Categories Tab is not clickable
- [ ] Fix the tabs component classes to not use two lines. However, the tabs should take minimal space.
- [ ] On categories details there is too much space on the top
    ![image](https://github.com/RobinNagpal/dodao-ui/assets/745748/a4cd50d5-d1fd-4fc6-a903-624e51ddb6ed)
- [ ] Test nicely the navigation of tidbits-collections and tidbits on arbiturm and uniswap, opportunity bank, and dodao-tidbits site

**Comment by MSamiTariq** [comment]
> Fixes
> 
> * [x]  Categories are not visible on the home page of Tidbits site
> * [x]  Tidbit Categories Tab is not clickable
> * [x]  Fix the tabs component classes to not use two lines. However, the tabs should take minimal space.
> * [x]  On categories details there is too much space on the top
>   ![image](https://private-user-images.githubusercontent.com/745748/316002160-a4cd50d5-d1fd-4fc6-a903-624e51ddb6ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTk2MDEsIm5iZiI6MTcxMTExOTMwMSwicGF0aCI6Ii83NDU3NDgvMzE2MDAyMTYwLWE0Y2Q1MGQ1LWQxZmQtNGZjNi1hOTAzLTYyNGU1MWRkYjZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNDU1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjE2NmZmZGI4ZGJkMTRiYzFkNmZkOTlmNmIyOTRiYjNhYTc3YTZjMzQ0NmUwZmJhNDczZGM1ZDcyMjI1MDI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aZU08Glh-8zaxgykrbdrNu9vk5--pxKlkb-KOLHYkXY)
> * [ ]  Test nicely the navigation of tidbits-collections and tidbits on arbiturm and uniswap, opportunity bank, and dodao-tidbits site

- Categories now visible on homepage
- Tidbit Categories Tab is now clickable
- Tabs now taking a single line, but the each tab is now of different size
- Fixed space issue
-  Tested the navigation of tidbits-collections and tidbits
