### ISSUE TITLE
V2 - Next set of improvements on Homepage of DoDAO.io and Tidbitshub.org

### ISSUE THREAD

**Issue by RobinNagpal** [RobinNagpal/dodao-ui#196]
@Neusha1  can you please list down the improvements here

**Comment by Neusha1** [comment]
I've listed down all the improvement points in this doc:

https://docs.google.com/document/d/1hkLDgtFoxfrjIaNbbjNhCBy4bfDk8b98rV7x8EyK6d0/edit
